export const newsData = {
  status: "ok",
  totalResults: 12007,
  articles: [
    {
      source: {
        id: null,
        name: "Forbes",
      },
      author: "Bianca Salonga, Contributor, \n Bianca Salonga, Contributor\n https://www.forbes.com/sites/biancasalonga/",
      title: "10 Beauty And Skincare Essentials For Summer",
      description: "From cosmetics to skincare and innovative formulations for sun protection, these essentials help to keep your summer beauty routines simple and effective",
      url: "https://www.forbes.com/sites/biancasalonga/2025/07/04/10-beauty-and-skincare-essentials-for-summer/",
      urlToImage: "https://imageio.forbes.com/specials-images/imageserve/6864c28917f5b15f6d626cb5/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
      publishedAt: "2025-07-04T05:17:00Z",
      content: "Summer skincare routines and makeup looks call for products that are lightweight, easy-to-use, and efficacious.\r\ngetty\r\nSummer is a magical season that brings with it promises of romance, adventure, … [+10282 chars]",
    },
    {
      source: {
        id: null,
        name: "Muycomputer.com",
      },
      author: "MuyComputer",
      title: "OMEN MAX 16 con procesador Intel® Core™ Ultra 9: HP reinventa el portátil gaming con potencia, control e inteligencia",
      description: "A todos nos encantan los portátiles gaming. Poder disfrutar de los títulos más exigentes en un equipo que cabe en la mochila y podemos llevar a cualquier parte los convierte en objeto de deseo para cualquier entusiasta del hardware. Pero combinar rendimiento …",
      url: "https://www.muycomputer.com/2025/07/04/omen-max-16-intel-core-ultra-9/",
      urlToImage: "https://www.muycomputer.com/wp-content/uploads/2025/07/image1-1000x600.jpg",
      publishedAt: "2025-07-04T05:16:16Z",
      content: "A todos nos encantan los portátiles gaming. Poder disfrutar de los títulos más exigentes en un equipo que cabe en la mochila y podemos llevar a cualquier parte los convierte en objeto de deseo para c… [+25778 chars]",
    },
    {
      source: {
        id: null,
        name: "Sapo.pt",
      },
      author: "Sportinforma",
      title: "Volta a Portugal feminina: Heidi Franz de amarelo após vencer segunda etapa",
      description: "Heidi Franz venceu esta quinta-feira a segunda etapa da Volta a Portugal feminina. A ciclista norte-americana da Cynisca Cycling foi a mais rápida a percorrer os 94,8 quilómetros entre Canelas e Águeda.Franz, que fez parte de um grupo que fugiu do pelotão a q…",
      url: "https://sportinforma.sapo.pt/modalidades/ciclismo/artigos/volta-a-portugal-feminina-heidi-franz-de-amarelo-apos-vencer-segunda-etapa",
      urlToImage: "https://thumbs.web.sapo.io/?W=1200&H=630&delay_optim=1&tv=1&crop=center&bottom_overlay=https%3A%2F%2Fsportinforma.sapo.pt%2Fassets%2Fimg%2Fdesporto-sapo%2Foverlay1.png&epic=MzUxChvH89K9nYO+cMgq2Mvk4/bH/mIWfPS+Byd8+Bjn1AS6C95215JN42Cn+QvRT6r/evILMOuf6TmtvHs/srT545ieFpCO6+23gYPTo8c96j0=",
      publishedAt: "2025-07-04T05:16:00Z",
      content: "Heidi Franz venceu esta quinta-feira a segunda etapa da Volta a Portugal feminina. A ciclista norte-americana da Cynisca Cycling foi a mais rápida a percorrer os 94,8 quilómetros entre Canelas e Águe… [+590 chars]",
    },
    {
      source: {
        id: null,
        name: "India Today",
      },
      author: "India Today Business Desk",
      title: "Gold gathering dust in locker? Financial advisor explains how to make it work",
      description: "A financial advisor has warned that family gold stored in lockers faces risk from rust floods and poor insurance He explains how a scheme can offer safety and steady returns instead",
      url: "https://www.indiatoday.in/business/personal-finance/story/gold-gathering-dust-in-locker-financial-advisor-explains-how-to-make-it-work-2750539-2025-07-04",
      urlToImage: "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202507/gold-price-today-020631260-16x9.jpg?VersionId=.cBYcxa4rF3klIXnHnbpSuya_W5ol7Ft",
      publishedAt: "2025-07-04T05:15:03Z",
      content: "What happens when the gold meant to secure your future quietly begins to decay in a bank locker?\r\nFinancial advisor Lovish Anand recently shared the story of a close friend who discovered that her fa… [+3286 chars]",
    },
    {
      source: {
        id: null,
        name: "Www.abc.es",
      },
      author: "(abc)",
      title: "Así han cambiado las notas de corte en Sevilla con el cambio de formato de Selectividad",
      description: "El cambio de formato de la Prueba de Acceso a la Universidad (PAU) , más conocida como Selectividad, ha repercutido en las notas de corte de la primera adjudicación. El porcentaje de aprobados en los exámenes realizados en primera convocatoria en la provincia…",
      url: "https://www.abc.es/sevilla/ciudad/cambiado-notas-corte-sevilla-cambio-formato-selectividad-20250704134547-nts.html",
      urlToImage: "https://s2.abcstatics.com/abc/www/multimedia/sevilla/2025/07/04/selectividad-examen-sevilla-U11666847024VzM-1024x512@diario_abc.jpg",
      publishedAt: "2025-07-04T05:14:03Z",
      content: "El cambio de formato de la Prueba de Acceso a la Universidad (PAU), más conocida como Selectividad, ha repercutido en las notas de corte de la primera adjudicación. El porcentaje de aprobados en los … [+4372 chars]",
    },
    {
      source: {
        id: null,
        name: "Globalsecurity.org",
      },
      author: "John Pike",
      title: "Is This The Summer That Russia Breaks Ukraine? (Not Likely)",
      description: "At one point during a grueling 110-day tour in the obliterated frontline Ukrainian city of Toretsk, Dmytro, a soldier with Ukraine's 100th Separate Mechanized Brigade, listened in to the radio traffic among Russian soldiers.",
      url: "https://www.globalsecurity.org/wmd/library/news/ukraine/2025/07/ukraine-250704-rferl01.htm",
      urlToImage: null,
      publishedAt: "2025-07-04T05:13:08Z",
      content: "By Yehor Lohinov and Mike Eckel July 04, 2025\r\nKRAMATORSK, Ukraine -- At one point during a grueling 110-day tour in the obliterated frontline Ukrainian city of Toretsk, Dmytro, a soldier with Ukrain… [+10111 chars]",
    },
    {
      source: {
        id: null,
        name: "Www.abc.es",
      },
      author: "(abc)",
      title: "El entierro de los túneles de la SE-40: la tuneladora acabó en la chatarra y volaron 145 millones de euros",
      description: "La decisión del ex director general de Carreteras Javier Herrero de enterrar los túneles en 2020 tuvo otras dos consecuencias directas, más allá de la parálisis definitiva de las obras al priorizar la del puente del Centenario y del cobro de mordidas en el co…",
      url: "https://www.abc.es/sevilla/ciudad/entierro-tuneles-se40-tuneladora-acabo-chatarra-volaron-20250704215531-nts.html",
      urlToImage: "https://s3.abcstatics.com/abc/www/multimedia/sevilla/2025/07/04/tuneladora-se40-U47368502348mKn-1024x512@diario_abc.jpeg",
      publishedAt: "2025-07-04T05:12:30Z",
      content: "La decisión del ex director general de Carreteras Javier Herrero de enterrar los túneles en 2020 tuvo otras dos consecuencias directas, más allá de la parálisis definitiva de las obras al priorizar l… [+2685 chars]",
    },
    {
      source: {
        id: null,
        name: "Www.abc.es",
      },
      author: "(abc)",
      title: "El alto cargo que enterró el túnel de la SE-40, en el centro de las mordidas",
      description: "Los túneles de la SE-40 son la mayor prueba de la desidia del Estado con Sevilla en cuanto a sus infraestructuras, y también del aprovechamiento político y personal que altos cargos del PSOE trataron de hacer hasta condenarlas para siempre. Ahora, con los aud…",
      url: "https://www.abc.es/sevilla/ciudad/alto-cargo-enterro-tunel-se40-centro-mordidas-20250704221032-nts.html",
      urlToImage: "https://s1.abcstatics.com/abc/www/multimedia/sevilla/2025/07/04/javier-herrero-se40-U28180422086UPY-1024x512@diario_abc.jpg",
      publishedAt: "2025-07-04T05:12:19Z",
      content: "Los túneles de la SE-40 son la mayor prueba de la desidia del Estado con Sevilla en cuanto a sus infraestructuras, y también del aprovechamiento político y personal que altos cargos del PSOE trataron… [+4822 chars]",
    },
    {
      source: {
        id: null,
        name: "Huffingtonpost.es",
      },
      author: "Redacción HuffPost / EP",
      title: "Consumo sanciona a siete empresas de comercio 'online' por impulsar falsas rebajas durante el Black Friday",
      description: "<![CDATA[<p>El Ministerio de Derechos Sociales, Consumo y Agenda 2030 ha sancionado a siete empresas de comercio 'online' por realizar falsas rebajas durante el 'Black Friday', con multas que se han elevado hasta cerca de los 350.000 euros por constituir infr…",
      url: "https://www.huffingtonpost.es/life/consumo/consumo-sanciona-siete-empresas-comercio-online-impulsar-falsas-rebajas-black-friday.html",
      urlToImage: "https://img.huffingtonpost.es/files/og_thumbnail/uploads/2024/11/25/imagen-de-archivo-de-un-escaparate-durante-el-black-friday.jpeg",
      publishedAt: "2025-07-04T05:11:07Z",
      content: "El Ministerio de Derechos Sociales, Consumo y Agenda 2030 ha sancionado a siete empresas de comercio 'online' por realizar falsas rebajas durante el 'Black Friday', con multas que se han elevado hast… [+2002 chars]",
    },
    {
      source: {
        id: null,
        name: "MediaNama.com",
      },
      author: "Sharveya Parasnis",
      title: "Proton Mail In Non-Compliance With IT Act: Govt To Karnataka HC",
      description: "The Centre's Additional Solicitor General in the Karnataka HC said that the Govt found Proton Mail not complying with India's IT Act.\nThe post Proton Mail In Non-Compliance With IT Act: Govt To Karnataka HC appeared first on MEDIANAMA.",
      url: "https://www.medianama.com/?p=281299",
      urlToImage: "https://www.medianama.com/wp-content/uploads/2020/10/email-3.jpg-3.jpg",
      publishedAt: "2025-07-04T05:08:19Z",
      content: "The Section 69A committee constituted by the Government to block Proton Mail found other unrelated compliance issues with the email service, stated the Additional Solicitor General to the Karnataka H… [+2323 chars]",
    },
    {
      source: {
        id: null,
        name: "BBC News",
      },
      author: null,
      title: "Shipyard needs urgent investment to survive, MSPs warn",
      description: "A Holyrood committee says a lack of orders and reputational damage need to be overcome for the Ferguson Marine yard to prosper.",
      url: "https://www.bbc.com/news/articles/ceq7y3wnpw4o",
      urlToImage: "https://ichef.bbci.co.uk/news/1024/branded_news/0749/live/30c5a870-580b-11f0-81c2-eddd1d437243.jpg",
      publishedAt: "2025-07-04T05:03:32Z",
      content: 'The Ferguson Marine shipyard in Port Glasgow was taken into public ownership in 2019\r\nThe publicly-owned Ferguson Marine shipyard needs "urgent investment" to become more competitive and survive, acc… [+4593 chars]',
    },
    {
      source: {
        id: null,
        name: "Louder",
      },
      author: "Dom Lawson",
      title: "“A lot of metalheads wind up finding prog – but it’s in a lot of their favourite bands already”: Progressive metal has never been healthier, and here’s why",
      description: "Members of Jinjer, Blood Incantation and Rivers Of Nihil explain the current rapid evolution of a genre that broke out 40 years ago",
      url: "https://www.loudersound.com/bands-artists/jinjer-blood-incantation-rivers-of-nihil-progressive-metal",
      urlToImage: "https://cdn.mos.cms.futurecdn.net/FgYnSAZ8sjX47NfdoGyK6j.jpg",
      publishedAt: "2025-07-04T05:03:00Z",
      content: "The progressive metal genre is currently undergoing a radical shift, with many extreme metal bands embracing their inner prog, and groups with an undeniable prog element playing bigger shows than eve… [+15556 chars]",
    },
    {
      source: {
        id: null,
        name: "The-independent.com",
      },
      author: "Vishwam Sankaran",
      title: "Scientists define six traits that make a person ‘cool’ – and they transcend borders",
      description: "Findings may help better understand role played by some traits in establishing social hierarchies",
      url: "https://www.the-independent.com/news/science/cool-personality-traits-psychology-b2782439.html",
      urlToImage: "https://static.the-independent.com/2025/07/02/3/54/Pedro-Pascal-attends-the-From-The-World-Of-John-Wick-Ballerina-world-premiere.jpeg?width=1200&height=800&crop=1200:800",
      publishedAt: "2025-07-04T05:02:09Z",
      content: "Your support helps us to tell the story\r\nFrom reproductive rights to climate change to Big Tech, The Independent is on the ground when the story is developing. Whether it's investigating the financia… [+3761 chars]",
    },
  ],
};
